### ISSUE TITLE
Update repository user permissions

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/gh-actions#21]
The repository user permissions are outdated and need to be adjusted.

**Comment by eddybrando** [comment]
@vabarbosa, I'm assigning this to you since I believe you have the necessary permissions to make this changes.

This doesn't have a high priority, so no rush.

**Comment by vabarbosa** [comment]
@eddybrando how/what permissions do we want to adjust? i guess one would be to give you appropriate access to also adjust permissions 😁

**Comment by vabarbosa** [comment]
done
